version: "3.7"

services:
  server:
    container_name: "server"
    build:
      dockerfile: ./devops/server.Dockerfile
      context: .

    command: ["python3", "./runserver.py"]
    ports:
      - "50001:50000"

  ts:
    container_name: "TS"
    build:
      dockerfile: ./devops/client.Dockerfile
      context: .

    command: ["python3", "runclient_ts.py"]
    depends_on:
      - server 
    environment:
      - SERVER_IP=server
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  ta1:
    container_name: "TA1"
    build:
      dockerfile: ./devops/client.Dockerfile
      context: .

    command: ["python3", "runclient_ta.py"]
    depends_on:
      - server 
    environment:
      - SERVER_IP=server
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  tv1:
    container_name: "TV1"
    build:
      dockerfile: ./devops/client.Dockerfile
      context: .

    command: ["python3", "runclient_tv.py"]
    depends_on:
      - server 
    environment:
      - SERVER_IP=server
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  # ta2:
  #   container_name: "TA2"
  #   build:
  #     dockerfile: ./devops/client.Dockerfile
  #     context: .

  #   command: ["python3", "runclient_ta.py"]
  #   depends_on:
  #     - server 
  #   environment:
  #     - SERVER_IP=server
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix

  # tv2:
  #   container_name: "TV2"
  #   build:
  #     dockerfile: ./devops/client.Dockerfile
  #     context: .

  #   command: ["python3", "runclient_tv.py"]
  #   depends_on:
  #     - server 
  #   environment:
  #     - SERVER_IP=server
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix

  # tv3:
  #   container_name: "TV3"
  #   build:
  #     dockerfile: ./devops/client.Dockerfile
  #     context: .

  #   command: ["python3", "runclient_tv.py"]
  #   depends_on:
  #     - server 
  #   environment:
  #     - SERVER_IP=server
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
